/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/dados/profissionais`; params?: Router.UnknownInputParams; } | { pathname: `/pages/atendimentos`; params?: Router.UnknownInputParams; } | { pathname: `/pages/login`; params?: Router.UnknownInputParams; } | { pathname: `/pages/profissionais`; params?: Router.UnknownInputParams; } | { pathname: `/pages/registro`; params?: Router.UnknownInputParams; } | { pathname: `/routes/navigation`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/dados/profissionais`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/atendimentos`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/login`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/profissionais`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/registro`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/navigation`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/dados/profissionais${`?${string}` | `#${string}` | ''}` | `/pages/atendimentos${`?${string}` | `#${string}` | ''}` | `/pages/login${`?${string}` | `#${string}` | ''}` | `/pages/profissionais${`?${string}` | `#${string}` | ''}` | `/pages/registro${`?${string}` | `#${string}` | ''}` | `/routes/navigation${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/dados/profissionais`; params?: Router.UnknownInputParams; } | { pathname: `/pages/atendimentos`; params?: Router.UnknownInputParams; } | { pathname: `/pages/login`; params?: Router.UnknownInputParams; } | { pathname: `/pages/profissionais`; params?: Router.UnknownInputParams; } | { pathname: `/pages/registro`; params?: Router.UnknownInputParams; } | { pathname: `/routes/navigation`; params?: Router.UnknownInputParams; };
    }
  }
}
